import "@/styles/globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import {  kalame, kalameBold } from '@/config/fonts';
import clsx from "clsx";
import { ToastContainer, toast } from 'react-toastify';
export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={clsx(` antialiased ${kalame.variable} ${kalameBold.variable}`, )}>
        <Providers>{children}
          <ToastContainer />
        </Providers>
      </body>
    </html>
  );
}
